### PR TITLE
Add support for external_includes

### LINKED ISSUE #266: rules_cuda ignores `external_includes` field in compilation context
`external_includes` was added in ~7.0.0 and rules_cuda ignore that field when merging CcInfos, which has the annoying effect that some deps are not made available to the compiler.

This is a placeholder to reference the issue in the code, and maybe propose a fix later.

### PR DESCRIPTION
**Pull request by layus**
With this PR I get a strange error about forbidden internal API.

Fixes #266

### CODE REVIEW

**Comment by cloudhan** [comment]
Seems comming from here https://togithub.com/bazelbuild/bazel/blob/3324f06cbd55ffadd497ca21e94ddb30a7675898/src/main/starlark/builtins_bzl/common/cc/cc_common.bzl#L454

**Comment by cloudhan** [comment]
There is a chain of something like `external_includes != _UNBOUND or \`, and the `external_includes` triggers the forbidden internal API..., looking into the `_PRIVATE_STARLARKIFICATION_ALLOWLIST` and you will notice the they are doing really dumb things and violate the open–closed principle by hardcoding the rule name... 🤦

**Comment by layus** [comment]
So it seems that external_includes are part of the internal API, and we are not supposed to use them. Maybe there is a way to merge compilation contexts without tearing it apart and recreating it like we do here ?

For now, I found a simple hotfix:

```bazel
cuda_library(
    ...
    features = ["-external_include_paths"],
)
```

**Comment by cloudhan** [comment]
I think it is workaroundable, you might just want to consume the external_includes (direct on the target or from deps), but dont propagate it forward by the cc_info.

**Pull request closed without merging**
