### PR TITLE
Move non glob files out of glob

### PR DESCRIPTION
**Pull request by hofbi**

### CODE REVIEW

**Review by jsharpe — APPROVED** [review]

**Comment by jsharpe** [comment]
Hmm, looks like the reason they're in the glob is to make them optional as they don't appear to be present in CI?

**Comment by hofbi** [comment]
Right, but this causes issues with `--incompatible_disallow_empty_glob` (at least in my case)

**Comment by cloudhan** [comment]
version.json and version.txt only exisits in specific versions, exclusively.

**Comment by hofbi** [comment]
Then should we better go for `allow_empty = True` in the `glob` function?

**Comment by cloudhan** [comment]
@hofbi Do we really need to set all globs to allow_empty=True?

**Comment by hofbi** [comment]
I just did it for all to avoid issues with `--incompatible_disallow_empty_glob` that are different than my own

**Review by cloudhan — APPROVED** [review]

**Pull request merged**
