### PR TITLE
Add flag "--host_copts" to specify global host copts

### PR DESCRIPTION
**Pull request by noaxp**

### CODE REVIEW

**Comment by cloudhan** [comment]
https://github.com/bazel-contrib/rules_cuda/blob/a2b9624fb9218b7360305f0cf57522e251d26c7b/cuda/private/rules/cuda_objects.bzl#L79-L79
is also needed to be updated.

**Comment by noaxp** [comment]
> https://github.com/bazel-contrib/rules_cuda/blob/a2b9624fb9218b7360305f0cf57522e251d26c7b/cuda/private/rules/cuda_objects.bzl#L79-L79
> 
> 
> is also needed to be updated.
> Better also update the `.bazelrc`s for flag alias

@cloudhan Flag alias added.
Not sure what I should update about `"host_copts": attr.string_list(doc = "Add these options to the CUDA host compilation command."), `, could you help to explain more?
Thank you~

**Comment by cloudhan** [comment]
Sorry, I mean, `_default_host_copts` attr in `cuda_objects` rule

**Comment by noaxp** [comment]
Fixed, thanks.

**Pull request merged**
